SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7  -- 7일 '이상'이므로 = 포함, 별칭 사용 가능
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;